package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublisherAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherAllPropertiesEquals(Publisher expected, Publisher actual) {
        assertPublisherAutoGeneratedPropertiesEquals(expected, actual);
        assertPublisherAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherAllUpdatablePropertiesEquals(Publisher expected, Publisher actual) {
        assertPublisherUpdatableFieldsEquals(expected, actual);
        assertPublisherUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherAutoGeneratedPropertiesEquals(Publisher expected, Publisher actual) {
        assertThat(expected)
            .as("Verify Publisher auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherUpdatableFieldsEquals(Publisher expected, Publisher actual) {
        assertThat(expected)
            .as("Verify Publisher relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublisherUpdatableRelationshipsEquals(Publisher expected, Publisher actual) {}
}
